steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '--platform linux/amd64', '-f', 'trainer.dockerfile', '-t',  'gcr.io/final-project-374512/trainer:latest', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/final-project-374512/trainer:latest']
timeout: 3600s