experiment_name: "exp_2"
model: "distilbert-base-uncased"
lr: 2e-4
epochs: 1
weight_decay: 0.01
batch_size: 8
max_steps: 1000
logging_steps: 100                    
eval_steps: 500                     
eval_accumulation_steps: 1        
load_best_model_at_end: True
