name: "Good coding practices test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Library sorting with isort
      run: |
        pip install isort
        isort .

    - name: Update formatting with black
      run: |
        pip install black
        black .

    - name: pep8 compliance with flake8
      run: |
        pip install flake8
        flake8 . --config .flake8