name: "Run tests"

on:
  push:
    branches: [ alaina ]
  pull_request:
    branches: [ alaina ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ matrix.os }}-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ matrix.os }}-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    # - uses: actions/checkout@v3
    # - uses: iterative/setup-dvc@v1
    # - name: Get data
    #   run: dvc pull
    #   env:
    #     GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest -v

    - name: Library sorting with isort
      run: |
        pip install isort
        isort .

    - name: Update formatting with black
      run: |
        pip install black
        black .

    - name: pep8 compliance with flake8
      run: |
        pip install flake8
        flake8 . --config .flake8